const loremTexts = [
  "Bacon ipsum dolor amet elit in lorem meatball tri-tip quis, shoulder chislic. Nostrud qui dolor biltong et cupidatat, meatloaf ham incididunt. Meatball nisi tail dolore labore sunt fugiat, t-bone anim quis chuck doner. Jowl tongue kevin, elit buffalo voluptate pig minim non. Ut picanha meatball salami sunt non. Jowl porchetta sausage, elit culpa kielbasa eiusmod fatback kevin pork belly sunt ham nisi nulla.",
  "Sunt tri-tip nostrud duis, pork doner ad sirloin dolor cow irure. Anim shank brisket, incididunt velit ut veniam esse ut tongue pig adipisicing chislic do excepteur. In shoulder cow, deserunt pastrami quis dolore biltong pancetta voluptate. Est ground round veniam nostrud ad ut ex picanha adipisicing pariatur. Voluptate non nulla filet mignon ball tip. Et pig nisi incididunt cow corned beef sunt, beef ribs doner. Biltong picanha nostrud alcatra beef tri-tip fatback.",
  "Nulla corned beef elit est enim consequat jowl et, frankfurter chicken alcatra anim meatball. Shankle leberkas consectetur jowl excepteur sed cupidatat veniam. Pork irure id cillum deserunt in. Occaecat do in leberkas, ball tip flank cupim quis shoulder tempor aliqua aute meatball.",
  "Ball tip biltong ut nisi in turducken landjaeger pancetta drumstick reprehenderit frankfurter shank. Incididunt chislic tri-tip ut, t-bone aute laboris pastrami shoulder proident laborum pork jerky nulla aliquip. Officia rump drumstick beef ribs pig short loin dolore boudin ad ipsum. Doner picanha ribeye, laboris bacon kielbasa filet mignon alcatra veniam ipsum fugiat id culpa. Corned beef sint andouille labore ipsum cow cupim.",
  "Pastrami laboris enim landjaeger ut, sausage id. Dolor occaecat ea, swine meatball t-bone proident. Ground round corned beef prosciutto shank drumstick ad, aliqua reprehenderit lorem venison jowl beef. Meatball consequat cow fugiat flank officia, filet mignon venison sint.",
  "Meatball tongue sunt consectetur laboris short ribs sint ham leberkas ground round jowl beef ribs. Hamburger cillum capicola enim ut ball tip ut laborum andouille pork loin picanha aliquip tail rump. Laborum hamburger cillum buffalo tri-tip labore laboris sint spare ribs. Consectetur spare ribs in cillum. Eiusmod consectetur est tenderloin.",
  "Bresaola jowl kielbasa pork loin et burgdoggen pastrami nisi culpa eiusmod minim pork chop fugiat reprehenderit cillum. Jerky tri-tip occaecat consectetur consequat, buffalo capicola jowl aliqua. Prosciutto elit boudin corned beef fugiat. Pork belly pancetta duis turkey tail cupim aute. Ea leberkas corned beef, magna kevin do strip steak commodo ham hock minim ad. Hamburger fatback dolore pig, do sirloin est salami excepteur ham hock swine pork rump nisi ribeye.",
  "Andouille labore pork belly kielbasa, pork chop veniam aliquip. T-bone chuck consectetur velit, non consequat sunt strip steak bacon nostrud swine commodo shank picanha short ribs. Spare ribs tenderloin ham hock chislic, elit chuck pork chop swine turkey. Adipisicing chicken enim fatback dolore exercitation.",
  "Chuck id commodo, landjaeger burgdoggen pastrami pariatur in hamburger shoulder proident. Pork belly kevin fatback, t-bone brisket corned beef velit kielbasa short ribs laboris dolore. Shank proident do salami deserunt alcatra buffalo quis in adipisicing venison spare ribs tri-tip pork belly. Exercitation dolore cillum voluptate incididunt dolor et lorem est ad laboris sint.",
  "Picanha porchetta aliquip ipsum minim salami eiusmod et magna ea reprehenderit pork belly. In ground round dolor reprehenderit, mollit fugiat filet mignon adipisicing lorem consectetur tongue chuck buffalo cupim pariatur. Tongue ad magna aliquip. Id landjaeger consectetur cupim chislic ham fugiat nulla et. Flank ut tenderloin, jowl esse cow ullamco aliquip est voluptate. Commodo anim andouille laborum chicken. Reprehenderit short ribs labore cillum tempor tenderloin.",
  "Landjaeger kevin short loin flank porchetta est short ribs sirloin proident chuck commodo. Voluptate lorem filet mignon non, in consequat porchetta bresaola minim nostrud nisi shoulder meatloaf. Frankfurter doner incididunt leberkas. Buffalo et shoulder adipisicing brisket prosciutto mollit swine eiusmod cupidatat ad.",
  "Porchetta hamburger eu, meatloaf beef exercitation short loin tri-tip pig adipisicing. Short ribs eiusmod ut, andouille pancetta quis velit. Pork loin qui enim eu, beef minim sausage voluptate velit non cillum. Veniam labore tongue leberkas, turkey id jerky consectetur venison occaecat cupim. Ball tip turkey esse pariatur. Enim tempor shankle chislic cillum rump laboris ad ea ribeye dolore pork belly in turkey ullamco.",
  "Minim sirloin tail, chuck sunt pork chicken sausage esse consectetur buffalo eu sint incididunt ut. Cow tempor pork strip steak dolor ribeye prosciutto. Ex pig adipisicing mollit aliqua alcatra commodo. Magna anim in sirloin fugiat shoulder cupim salami sint short ribs.",
  "Proident pork belly dolore landjaeger, venison jowl pariatur shoulder et. Quis cupim excepteur, deserunt short loin in consequat spare ribs anim culpa tail. Ea ipsum est porchetta, jowl ullamco jerky ribeye pig sed bacon hamburger reprehenderit. Rump turkey ut in culpa, pig jowl swine enim. In chislic pork belly lorem. Ut pariatur buffalo chislic bacon chicken consequat brisket tongue cupidatat commodo tenderloin. Enim ribeye alcatra landjaeger eu sunt.",
  "Porchetta pork chop t-bone cillum duis, ex sausage pork beef. Turducken alcatra esse consectetur. Est incididunt chislic eiusmod. Shoulder culpa biltong leberkas in duis. T-bone landjaeger nisi, hamburger flank deserunt drumstick alcatra ullamco ut in pork belly in.",
];

function randomNumber(min, max) {
  return Math.round(Math.random() * (max - min) + min);
}

export const loremIpsum = (numOfParagraphs) => {
  const getRandomParagraph = () =>
    loremTexts[randomNumber(0, loremTexts.length)];
  return [...Array(numOfParagraphs)].map(getRandomParagraph).join("\n");
};
